#Chi Square
swirl_options(swirl_logging = TRUE)
#chi square cheating or not
CheatData<- structure(list(repCor = c("Overreported", "Told Truth", "Told Truth", 
                                      "Overreported", "Told Truth", "Told Truth", "Told Truth", "Told Truth", 
                                      "Told Truth", "Told Truth", "Overreported", "Told Truth", "Told Truth", 
                                      "Told Truth", "Overreported", "Overreported", "Overreported", "Told Truth", 
                                      "Overreported", "Told Truth", "Overreported", "Overreported", "Told Truth", 
                                      "Told Truth", "Told Truth", "Told Truth", "Told Truth", "Told Truth", 
                                      "Overreported", "Told Truth", "Told Truth", "Told Truth", "Told Truth", 
                                      "Overreported", "Overreported", "Overreported", "Overreported", "Told Truth", 
                                      "Overreported", "Told Truth", "Told Truth", "Told Truth", "Told Truth", 
                                      "Told Truth", "Overreported", "Overreported", "Told Truth", "Told Truth", 
                                      "Overreported", "Told Truth", "Told Truth", "Told Truth", "Told Truth", 
                                      "Overreported", "Overreported", "Overreported", "Told Truth", "Told Truth", 
                                      "Overreported", "Told Truth", "Overreported", "Told Truth", "Overreported", 
                                      "Overreported", "Told Truth", "Overreported", "Told Truth", "Told Truth", 
                                      "Told Truth", "Overreported", "Overreported", "Told Truth", "Overreported", 
                                      "Overreported", "Overreported", "Overreported", "Told Truth", "Overreported", 
                                      "Overreported", "Overreported", "Told Truth", "Told Truth", "Told Truth", 
                                      "Overreported", "Told Truth", "Told Truth", "Told Truth", "Overreported", 
                                      "Overreported", "Told Truth", "Told Truth", "Told Truth", "Told Truth", 
                                      "Told Truth", "Told Truth", "Told Truth", "Told Truth", "Overreported", 
                                      "Overreported", "Overreported", "Overreported", "Overreported", "Told Truth", 
                                      "Told Truth", "Told Truth", "Told Truth", "Overreported", "Told Truth", 
                                      "Told Truth", "Told Truth", "Told Truth", "Told Truth", "Overreported", 
                                      "Overreported", "Told Truth", "Told Truth", "Told Truth", "Told Truth", 
                                      "Told Truth", "Overreported", "Told Truth", "Overreported", "Told Truth", 
                                      "Told Truth", "Told Truth", "Overreported", "Told Truth", "Told Truth", 
                                      "Told Truth", "Told Truth", "Overreported", "Told Truth", "Overreported", 
                                      "Told Truth", "Told Truth", "Told Truth", "Overreported", "Told Truth", 
                                      "Told Truth", "Told Truth", "Told Truth", "Told Truth", "Told Truth", 
                                      "Told Truth", "Told Truth", "Told Truth", "Told Truth", "Told Truth", 
                                      "Told Truth", "Told Truth", "Told Truth", "Told Truth", "Overreported", 
                                      "Told Truth", "Told Truth", "Told Truth", "Told Truth", "Told Truth", 
                                      "Told Truth", "Told Truth", "Told Truth", "Told Truth", "Told Truth", 
                                      "Told Truth", "Told Truth", "Told Truth", "Told Truth", "Told Truth", 
                                      "Overreported", "Told Truth", "Told Truth", "Told Truth", "Told Truth", 
                                      "Told Truth", "Told Truth", "Overreported", "Told Truth", "Told Truth", 
                                      "Told Truth", "Told Truth", "Told Truth", "Told Truth", "Told Truth", 
                                      "Overreported", "Told Truth", "Told Truth", "Told Truth", "Told Truth", 
                                      "Told Truth", "Overreported", "Told Truth", "Overreported", "Told Truth", 
                                      "Told Truth", "Told Truth", "Told Truth", "Told Truth", "Told Truth", 
                                      "Told Truth", "Told Truth", "Told Truth", "Told Truth", "Told Truth", 
                                      "Overreported", "Overreported", "Told Truth", "Told Truth", "Told Truth", 
                                      "Overreported", "Told Truth", "Overreported", "Told Truth", "Told Truth", 
                                      "Told Truth", "Told Truth", "Told Truth", "Told Truth", "Told Truth", 
                                      "Told Truth", "Told Truth", "Told Truth", "Told Truth", "Told Truth", 
                                      "Told Truth", "Told Truth", "Told Truth", "Overreported", "Overreported", 
                                      "Overreported", "Told Truth", "Told Truth", "Told Truth", "Told Truth"
), cirCor = c("Circled More", "Circled Correct", "Circled Correct", 
              "Circled More", "Circled Correct", "Circled Correct", "Circled Correct", 
              "Circled Correct", "Circled Correct", "Circled Correct", "Circled More", 
              "Circled Correct", "Circled Correct", "Circled Correct", "Circled More", 
              "Circled More", "Circled More", "Circled Correct", "Circled Correct", 
              "Circled Correct", "Circled More", "Circled Correct", "Circled Correct", 
              "Circled Correct", "Circled Correct", "Circled Correct", "Circled More", 
              "Circled Correct", "Circled More", "Circled More", "Circled Correct", 
              "Circled Correct", "Circled Correct", "Circled More", "Circled More", 
              "Circled More", "Circled More", "Circled More", "Circled More", 
              "Circled Correct", "Circled Correct", "Circled Correct", "Circled Correct", 
              "Circled More", "Circled More", "Circled More", "Circled Correct", 
              "Circled Correct", "Circled More", "Circled More", "Circled Correct", 
              "Circled Correct", "Circled More", "Circled More", "Circled Correct", 
              "Circled More", "Circled Correct", "Circled Correct", "Circled More", 
              "Circled More", "Circled More", "Circled More", "Circled More", 
              "Circled More", "Circled Correct", "Circled More", "Circled Correct", 
              "Circled Correct", "Circled Correct", "Circled More", "Circled More", 
              "Circled More", "Circled More", "Circled More", "Circled More", 
              "Circled More", "Circled Correct", "Circled Correct", "Circled More", 
              "Circled More", "Circled Correct", "Circled Correct", "Circled Correct", 
              "Circled More", "Circled Correct", "Circled Correct", "Circled Correct", 
              "Circled More", "Circled More", "Circled More", "Circled Correct", 
              "Circled More", "Circled More", "Circled Correct", "Circled Correct", 
              "Circled More", "Circled Correct", "Circled Correct", "Circled More", 
              "Circled More", "Circled More", "Circled More", "Circled Correct", 
              "Circled Correct", "Circled Correct", "Circled Correct", "Circled More", 
              "Circled Correct", "Circled More", "Circled Correct", "Circled Correct", 
              "Circled Correct", "Circled More", "Circled More", "Circled Correct", 
              "Circled Correct", "Circled Correct", "Circled More", "Circled More", 
              "Circled More", "Circled More", "Circled More", "Circled Correct", 
              "Circled More", "Circled Correct", "Circled More", "Circled More", 
              "Circled More", "Circled Correct", "Circled Correct", "Circled Correct", 
              "Circled Correct", "Circled Correct", "Circled More", "Circled More", 
              "Circled Correct", "Circled Correct", "Circled Correct", "Circled More", 
              "Circled More", "Circled Correct", "Circled Correct", "Circled More", 
              "Circled Correct", "Circled More", "Circled Correct", "Circled More", 
              "Circled More", "Circled Correct", "Circled More", "Circled Correct", 
              "Circled Correct", "Circled Correct", "Circled More", "Circled Correct", 
              "Circled Correct", "Circled Correct", "Circled Correct", "Circled More", 
              "Circled More", "Circled More", "Circled More", "Circled Correct", 
              "Circled Correct", "Circled More", "Circled Correct", "Circled Correct", 
              "Circled More", "Circled Correct", "Circled Correct", "Circled Correct", 
              "Circled Correct", "Circled Correct", "Circled More", "Circled More", 
              "Circled More", "Circled Correct", "Circled More", "Circled Correct", 
              "Circled More", "Circled Correct", "Circled More", "Circled Correct", 
              "Circled More", "Circled Correct", "Circled Correct", "Circled Correct", 
              "Circled More", "Circled More", "Circled More", "Circled More", 
              "Circled More", "Circled More", "Circled Correct", "Circled More", 
              "Circled Correct", "Circled More", "Circled Correct", "Circled Correct", 
              "Circled Correct", "Circled Correct", "Circled More", "Circled More", 
              "Circled More", "Circled More", "Circled More", "Circled More", 
              "Circled Correct", "Circled Correct", "Circled Correct", "Circled Correct", 
              "Circled Correct", "Circled More", "Circled More", "Circled Correct", 
              "Circled More", "Circled Correct", "Circled More", "Circled More", 
              "Circled More", "Circled More", "Circled Correct", "Circled More", 
              "Circled More", "Circled More", "Circled Correct", "Circled More", 
              "Circled Correct", "Circled More", "Circled Correct", "Circled Correct", 
              "Circled Correct", "Circled More"), condition = c("regular", 
                                                                "regular", "regular", "regular", "regular", "regular", "regular", 
                                                                "regular", "regular", "regular", "regular", "regular", "regular", 
                                                                "regular", "regular", "regular", "regular", "regular", "regular", 
                                                                "regular", "regular", "regular", "regular", "regular", "regular", 
                                                                "regular", "regular", "regular", "regular", "regular", "regular", 
                                                                "regular", "regular", "regular", "regular", "regular", "regular", 
                                                                "regular", "regular", "regular", "regular", "regular", "regular", 
                                                                "regular", "regular", "regular", "regular", "regular", "regular", 
                                                                "regular", "regular", "regular", "regular", "regular", "regular", 
                                                                "regular", "regular", "regular", "regular", "regular", "regular", 
                                                                "regular", "regular", "regular", "regular", "regular", "regular", 
                                                                "regular", "regular", "regular", "regular", "regular", "regular", 
                                                                "regular", "regular", "regular", "regular", "regular", "regular", 
                                                                "regular", "regular", "regular", "regular", "regular", "regular", 
                                                                "regular", "regular", "regular", "regular", "regular", "regular", 
                                                                "regular", "regular", "regular", "regular", "regular", "regular", 
                                                                "regular", "regular", "regular", "regular", "regular", "regular", 
                                                                "regular", "regular", "regular", "regular", "regular", "regular", 
                                                                "regular", "regular", "regular", "regular", "regular", "regular", 
                                                                "check", "check", "check", "check", "check", "check", "check", 
                                                                "check", "check", "check", "check", "check", "check", "check", 
                                                                "check", "check", "check", "check", "check", "check", "check", 
                                                                "check", "check", "check", "check", "check", "check", "check", 
                                                                "check", "check", "check", "check", "check", "check", "check", 
                                                                "check", "check", "check", "check", "check", "check", "check", 
                                                                "check", "check", "check", "check", "check", "check", "check", 
                                                                "check", "check", "check", "check", "check", "check", "check", 
                                                                "check", "check", "check", "check", "check", "check", "check", 
                                                                "check", "check", "check", "check", "check", "check", "check", 
                                                                "check", "check", "check", "check", "check", "check", "check", 
                                                                "check", "check", "check", "check", "check", "check", "check", 
                                                                "check", "check", "check", "check", "check", "check", "check", 
                                                                "check", "check", "check", "check", "check", "check", "check", 
                                                                "check", "check", "check", "check", "check", "check", "check", 
                                                                "check", "check", "check", "check", "check", "check", "check", 
                                                                "check", "check", "check", "check", "check", "check")), row.names = c(1L, 
                                                                                                                                      2L, 3L, 4L, 5L, 6L, 9L, 10L, 11L, 13L, 14L, 15L, 16L, 18L, 19L, 
                                                                                                                                      20L, 21L, 23L, 24L, 25L, 26L, 27L, 28L, 29L, 30L, 31L, 32L, 33L, 
                                                                                                                                      34L, 36L, 37L, 38L, 39L, 40L, 41L, 43L, 44L, 45L, 46L, 48L, 49L, 
                                                                                                                                      50L, 51L, 52L, 53L, 54L, 55L, 56L, 57L, 58L, 61L, 62L, 63L, 65L, 
                                                                                                                                      66L, 67L, 68L, 69L, 70L, 72L, 73L, 74L, 75L, 76L, 79L, 80L, 81L, 
                                                                                                                                      82L, 83L, 84L, 85L, 86L, 87L, 88L, 89L, 90L, 91L, 92L, 93L, 94L, 
                                                                                                                                      95L, 96L, 97L, 99L, 102L, 103L, 104L, 105L, 106L, 107L, 108L, 
                                                                                                                                      109L, 110L, 111L, 112L, 113L, 114L, 115L, 117L, 118L, 119L, 120L, 
                                                                                                                                      121L, 122L, 123L, 124L, 125L, 126L, 127L, 128L, 129L, 130L, 131L, 
                                                                                                                                      132L, 133L, 134L, 135L, 136L, 137L, 138L, 139L, 140L, 141L, 142L, 
                                                                                                                                      143L, 144L, 145L, 146L, 147L, 148L, 149L, 150L, 151L, 152L, 153L, 
                                                                                                                                      154L, 155L, 156L, 157L, 158L, 159L, 162L, 163L, 164L, 166L, 167L, 
                                                                                                                                      168L, 169L, 170L, 171L, 172L, 173L, 174L, 175L, 176L, 177L, 179L, 
                                                                                                                                      180L, 181L, 182L, 184L, 185L, 186L, 187L, 188L, 190L, 191L, 192L, 
                                                                                                                                      193L, 194L, 195L, 196L, 197L, 198L, 200L, 201L, 202L, 203L, 204L, 
                                                                                                                                      205L, 206L, 207L, 208L, 209L, 210L, 211L, 212L, 213L, 214L, 216L, 
                                                                                                                                      217L, 218L, 219L, 220L, 221L, 222L, 223L, 224L, 225L, 227L, 228L, 
                                                                                                                                      229L, 230L, 231L, 232L, 234L, 235L, 236L, 237L, 239L, 240L, 243L, 
                                                                                                                                      244L, 245L, 246L, 247L, 248L, 249L, 250L, 251L, 252L, 253L, 254L, 
                                                                                                                                      255L, 257L, 258L, 261L, 262L, 264L, 265L, 266L, 267L, 268L), class = "data.frame")

