---
title: "Psychology Statistics"
---

### Authors

- Kevin R. Carriere
- Jason Kilgore

### Description

This course is meant to be paired with an Undergraduate Research Methods or Statistics course. It is meant to help teach students basic statistics using R in an interactive framework. We take open data and replicate the results (or discuss why sometimes we cannot replicate the results). Future directions of this course include a lesson on sum of squares and additional practice using the tidyverse and ggplot2 packages. It is imagined that by the end of this course, students should be able to build their own graphs from their research methods projects. Students interact with the following packages throughout this course: dplyr, ggplot2, plyr, and psych, and also installed for backend use is MASS, imager, wesanderson, and UsingR.

This course does not cover Baysian Statistics.

This course was supported through the Society for the Improvement of Psychological Science (SIPS) Grants-In-Aid to Reduce Barriers to Improving Psychological Science.

### Installation

```r
swirl::install_course("PSYCH")
```

#### Manual Installation

1. Download [this](http://swirlstats.com/scn/PSYCH.swc) file.
2. Run `swirl::install_course()` in the R console.
3. Select the file you just downloaded.

### Website

- https://github.com/krcarriere/Psychology_Statistics

### Future Plans

- Consider making the hints actually hint-y. Currently, all hints just give the answer.

- Look for collaborators! Are you interested in using this in your course? Can we A/B test to see if it helps?