#Regression

swirl_options(swirl_logging = TRUE)

gamesdf <- structure(list(Condition = c("Selfish", "Selfish", "Selfish", 
                             "Nice", "Selfish", "Selfish", "Selfish", "Nice", "Nice", "Selfish", 
                             "Nice", "Selfish", "Nice", "Nice", "Nice", "Nice", "Selfish", 
                             "Selfish", "Selfish", "Nice", "Selfish", "Selfish", "Nice", "Selfish", 
                             "Selfish", "Selfish", "Selfish", "Nice", "Nice", "Selfish", "Selfish", 
                             "Nice", "Nice", "Selfish", "Selfish", "Selfish", "Selfish", "Selfish", 
                             "Nice", "Selfish", "Selfish", "Selfish", "Nice", "Nice", "Selfish", 
                             "Selfish", "Selfish", "Selfish", "Nice", "Selfish", "Nice", "Selfish", 
                             "Nice", "Nice", "Selfish", "Nice", "Nice", "Selfish", "Selfish", 
                             "Nice", "Selfish", "Selfish", "Selfish", "Selfish", "Selfish", 
                             "Selfish", "Nice", "Selfish", "Nice", "Nice", "Selfish", "Nice", 
                             "Selfish", "Nice", "Nice", "Nice", "Nice", "Selfish", "Selfish", 
                             "Selfish", "Nice", "Nice", "Nice", "Nice", "Selfish", "Nice", 
                             "Selfish", "Selfish", "Selfish", "Selfish", "Nice", "Nice", "Selfish", 
                             "Selfish", "Selfish", "Selfish", "Selfish", "Nice", "Selfish", 
                             "Selfish", "Nice", "Selfish", "Nice", "Selfish", "Nice", "Selfish", 
                             "Nice", "Selfish", "Nice", "Nice", "Selfish", "Nice", "Nice", 
                             "Nice", "Selfish", "Selfish", "Selfish", "Selfish", "Nice", "Nice", 
                             "Nice", "Nice", "Nice", "Selfish", "Selfish", "Selfish", "Selfish", 
                             "Nice", "Selfish", "Selfish", "Selfish", "Nice", "Selfish", "Nice", 
                             "Selfish", "Nice", "Selfish", "Selfish", "Nice", "Selfish", "Selfish", 
                             "Nice", "Nice", "Nice", "Selfish", "Selfish", "Selfish", "Nice", 
                             "Nice", "Nice", "Selfish", "Nice", "Selfish", "Nice", "Selfish", 
                             "Selfish", "Nice", "Nice", "Nice", "Selfish", "Selfish", "Nice", 
                             "Selfish", "Nice", "Selfish", "Selfish", "Selfish", "Selfish", 
                             "Selfish", "Nice", "Nice", "Nice", "Selfish", "Selfish", "Selfish", 
                             "Nice", "Nice", "Selfish", "Nice", "Selfish", "Selfish", "Nice", 
                             "Nice", "Selfish", "Nice", "Nice", "Nice", "Selfish", "Nice", 
                             "Nice", "Nice", "Selfish", "Nice", "Nice", "Selfish", "Nice", 
                             "Nice", "Nice", "Nice", "Nice", "Nice", "Selfish", "Selfish", 
                             "Nice", "Selfish", "Selfish", "Selfish", "Nice", "Selfish", "Nice", 
                             "Selfish", "Selfish", "Selfish", "Selfish", "Nice", "Nice", "Nice", 
                             "Nice", "Nice", "Selfish", "Nice", "Nice", "Selfish", "Nice", 
                             "Nice", "Selfish", "Nice", "Nice", "Selfish", "Nice", "Nice", 
                             "Nice", "Selfish", "Nice", "Nice", "Selfish", "Nice", "Nice", 
                             "Selfish", "Nice", "Nice", "Nice", "Selfish", "Selfish", "Nice", 
                             "Selfish", "Selfish", "Selfish", "Selfish", "Selfish", "Selfish", 
                             "Nice", "Selfish", "Selfish", "Selfish", "Nice", "Nice", "Selfish", 
                             "Nice", "Selfish", "Selfish", "Nice", "Nice", "Nice", "Nice", 
                             "Nice", "Nice", "Selfish", "Selfish", "Selfish", "Selfish", "Selfish", 
                             "Selfish", "Selfish", "Nice", "Selfish", "Selfish", "Nice", "Nice", 
                             "Nice", "Selfish", "Nice", "Nice", "Nice", "Nice", "Nice", "Nice", 
                             "Nice", "Selfish", "Selfish", "Selfish", "Selfish", "Nice", "Nice", 
                             "Selfish", "Selfish", "Selfish", "Selfish", "Selfish", "Nice", 
                             "Nice", "Selfish", "Nice", "Selfish", "Selfish", "Nice", "Nice", 
                             "Selfish", "Selfish", "Nice", "Nice", "Selfish", "Selfish", "Selfish", 
                             "Selfish", "Nice", "Selfish", "Selfish", "Selfish", "Nice", "Selfish", 
                             "Selfish", "Selfish", "Selfish", "Nice", "Selfish", "Selfish", 
                             "Selfish", "Nice", "Selfish", "Selfish", "Nice", "Nice", "Selfish", 
                             "Selfish", "Selfish", "Nice", "Selfish", "Nice", "Selfish", "Nice", 
                             "Selfish", "Selfish", "Nice", "Selfish", "Selfish", "Nice", "Nice", 
                             "Nice", "Selfish", "Nice", "Nice", "Nice", "Selfish", "Nice", 
                             "Selfish", "Nice", "Selfish", "Selfish", "Selfish", "Nice", "Selfish", 
                             "Selfish", "Nice", "Selfish", "Nice", "Nice", "Selfish", "Nice", 
                             "Selfish", "Nice", "Selfish", "Selfish", "Nice", "Nice", "Nice", 
                             "Nice", "Selfish", "Nice", "Nice", "Selfish", "Nice", "Nice", 
                             "Selfish", "Nice", "Nice", "Selfish", "Nice", "Selfish", "Selfish", 
                             "Selfish", "Selfish", "Nice", "Nice", "Selfish", "Nice", "Selfish", 
                             "Nice", "Selfish", "Nice", "Selfish", "Selfish", "Nice", "Selfish", 
                             "Nice", "Selfish", "Nice", "Nice", "Nice"), TargetTrial = c(1, 
                                                                                         0, 0, 0, 1, 0, 0, 1, 1, 1, 0, 1, 1, 1, 1, 1, 0, 1, 1, 0, 1, 1, 
                                                                                         1, 1, 0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 0, 0, 1, 0, 1, 1, 1, 0, 1, 
                                                                                         1, 0, 1, 0, 0, 1, 1, 1, 0, 1, 0, 0, 1, 1, 1, 1, 1, 0, 0, 1, 1, 
                                                                                         0, 1, 1, 1, 1, 1, 0, 1, 1, 0, 1, 1, 1, 1, 1, 0, 1, 1, 0, 1, 0, 
                                                                                         0, 1, 1, 0, 1, 1, 0, 0, 1, 1, 1, 0, 1, 0, 0, 1, 0, 1, 0, 1, 0, 
                                                                                         1, 1, 0, 0, 0, 0, 1, 1, 0, 1, 0, 1, 1, 1, 1, 1, 0, 1, 1, 0, 0, 
                                                                                         1, 1, 1, 0, 1, 1, 1, 1, 1, 0, 0, 0, 1, 0, 0, 0, 1, 1, 0, 0, 1, 
                                                                                         0, 1, 1, 1, 1, 1, 0, 1, 0, 0, 1, 0, 0, 0, 0, 1, 0, 1, 0, 0, 0, 
                                                                                         1, 1, 1, 1, 0, 1, 1, 1, 0, 0, 0, 1, 1, 1, 0, 1, 0, 1, 0, 1, 0, 
                                                                                         0, 0, 1, 0, 0, 1, 1, 0, 1, 1, 0, 0, 1, 1, 1, 0, 1, 1, 0, 0, 1, 
                                                                                         0, 1, 1, 1, 0, 1, 0, 0, 1, 0, 1, 1, 0, 1, 1, 1, 1, 1, 1, 1, 1, 
                                                                                         1, 0, 0, 1, 1, 1, 0, 0, 1, 1, 1, 0, 0, 1, 1, 0, 0, 1, 1, 1, 1, 
                                                                                         0, 0, 0, 1, 1, 1, 0, 0, 1, 1, 0, 0, 1, 1, 1, 1, 0, 0, 1, 0, 1, 
                                                                                         0, 1, 0, 1, 1, 1, 1, 1, 0, 1, 1, 0, 0, 0, 1, 0, 1, 0, 0, 0, 1, 
                                                                                         1, 1, 0, 1, 1, 1, 1, 0, 1, 0, 1, 0, 1, 0, 0, 1, 1, 1, 1, 0, 1, 
                                                                                         1, 1, 1, 1, 0, 1, 0, 0, 1, 0, 1, 1, 0, 0, 1, 1, 1, 1, 0, 1, 1, 
                                                                                         0, 0, 1, 0, 0, 1, 1, 0, 1, 0, 0, 1, 1, 1, 1, 1, 1, 0, 1, 1, 0, 
                                                                                         0, 1, 1, 0, 1, 1, 0, 1, 1, 1, 0, 0, 1, 1, 1, 0, 1, 1, 1, 0, 0, 
                                                                                         0, 1, 1, 0, 1, 0, 1, 0, 0, 0, 0, 1, 1, 1, 0, 0, 1, 0, 1, 0, 0, 
                                                                                         0, 0, 1, 1, 1, 0, 1, 0, 0), AllocatorRating = c(3L, 2L, 4L, 6L, 
                                                                                                                                       2L, 2L, 5L, 7L, 7L, 6L, 7L, 7L, 5L, 6L, 7L, 6L, 6L, 5L, 1L, 3L, 
                                                                                                                                       7L, 6L, 3L, 2L, 3L, 5L, 1L, 4L, 3L, 3L, 3L, 6L, 7L, 4L, 4L, 4L, 
                                                                                                                                       5L, 1L, 7L, 4L, 1L, 4L, 6L, 5L, 6L, 2L, 6L, 4L, 4L, 5L, 6L, 4L, 
                                                                                                                                       6L, 2L, 4L, 7L, 7L, 7L, 4L, 7L, 2L, 4L, 5L, 7L, 4L, 1L, 7L, 1L, 
                                                                                                                                       4L, 7L, 3L, 5L, 7L, 7L, 7L, 5L, 5L, 3L, 5L, 1L, 5L, 5L, 2L, 7L, 
                                                                                                                                       1L, 2L, 2L, 3L, 4L, 2L, 4L, 7L, 2L, 4L, 6L, 2L, 1L, 7L, 4L, 3L, 
                                                                                                                                       6L, 3L, 7L, 1L, 7L, 3L, 6L, 4L, 5L, 3L, 2L, 3L, 3L, 5L, 4L, 7L, 
                                                                                                                                       4L, 5L, 6L, 7L, 5L, 6L, 6L, 5L, 4L, 2L, 4L, 5L, 5L, 6L, 1L, 7L, 
                                                                                                                                       3L, 6L, 5L, 7L, 1L, 4L, 4L, 2L, 5L, 4L, 4L, 6L, 3L, 2L, 1L, 7L, 
                                                                                                                                       5L, 2L, 6L, 6L, 5L, 7L, 6L, 5L, 4L, 4L, 6L, 4L, 2L, 4L, 2L, 7L, 
                                                                                                                                       2L, 3L, 1L, 2L, 5L, 6L, 5L, 6L, 4L, 1L, 7L, 7L, 6L, 3L, 7L, 1L, 
                                                                                                                                       5L, 6L, 7L, 6L, 4L, 4L, 7L, 3L, 6L, 6L, 5L, 4L, 5L, 6L, 1L, 6L, 
                                                                                                                                       7L, 5L, 7L, 6L, 6L, 1L, 3L, 7L, 7L, 3L, 4L, 6L, 4L, 3L, 5L, 2L, 
                                                                                                                                       3L, 6L, 5L, 4L, 4L, 6L, 3L, 3L, 1L, 6L, 4L, 4L, 6L, 7L, 7L, 6L, 
                                                                                                                                       3L, 7L, 7L, 5L, 6L, 4L, 5L, 5L, 3L, 6L, 4L, 4L, 5L, 7L, 3L, 5L, 
                                                                                                                                       6L, 5L, 4L, 4L, 2L, 6L, 7L, 6L, 4L, 2L, 3L, 2L, 6L, 3L, 7L, 4L, 
                                                                                                                                       2L, 7L, 7L, 4L, 3L, 6L, 7L, 5L, 2L, 1L, 2L, 5L, 3L, 4L, 5L, 6L, 
                                                                                                                                       4L, 7L, 7L, 6L, 4L, 5L, 7L, 6L, 7L, 6L, 4L, 4L, 2L, 5L, 2L, 2L, 
                                                                                                                                       4L, 4L, 6L, 6L, 3L, 3L, 2L, 4L, 7L, 2L, 5L, 2L, 2L, 7L, 2L, 6L, 
                                                                                                                                       1L, 4L, 6L, 4L, 4L, 3L, 2L, 7L, 3L, 6L, 5L, 6L, 3L, 1L, 3L, 7L, 
                                                                                                                                       7L, 7L, 5L, 3L, 7L, 6L, 6L, 5L, 5L, 4L, 3L, 7L, 6L, 3L, 5L, 3L, 
                                                                                                                                       6L, 3L, 6L, 6L, 4L, 7L, 6L, 3L, 7L, 7L, 7L, 5L, 7L, 4L, 2L, 2L, 
                                                                                                                                       7L, 3L, 5L, 3L, 4L, 1L, 6L, 4L, 4L, 5L, 5L, 4L, 6L, 5L, 5L, 2L, 
                                                                                                                                       2L, 4L, 6L, 7L, 5L, 5L, 3L, 6L, 2L, 5L, 6L, 6L, 3L, 5L, 4L, 1L, 
                                                                                                                                       1L, 1L, 4L, 6L, 7L, 3L, 3L, 6L, 1L, 6L, 2L, 1L, 4L, 3L, 3L, 2L, 
                                                                                                                                       7L, 3L, 5L, 1L, 4L), ReceiverRating = c(6L, 6L, 7L, 5L, 5L, 4L, 
                                                                                                                                                                              5L, 7L, 7L, 5L, 5L, 4L, 7L, 7L, 7L, 7L, 7L, 6L, 4L, 4L, 7L, 6L, 
                                                                                                                                                                              4L, 7L, 5L, 7L, 5L, 5L, 4L, 4L, 5L, 7L, 7L, 6L, 4L, 4L, 5L, 5L, 
                                                                                                                                                                              5L, 5L, 6L, 4L, 5L, 5L, 7L, 4L, 6L, 4L, 5L, 4L, 7L, 5L, 4L, 6L, 
                                                                                                                                                                              7L, 7L, 7L, 6L, 4L, 4L, 6L, 6L, 5L, 7L, 3L, 7L, 7L, 5L, 5L, 4L, 
                                                                                                                                                                              5L, 5L, 7L, 6L, 7L, 4L, 5L, 4L, 6L, 5L, 4L, 4L, 4L, 7L, 4L, 4L, 
                                                                                                                                                                              5L, 4L, 4L, 7L, 4L, 5L, 5L, 5L, 7L, 4L, 7L, 7L, 5L, 5L, 6L, 5L, 
                                                                                                                                                                              7L, 7L, 7L, 7L, 4L, 4L, 6L, 5L, 5L, 7L, 4L, 6L, 4L, 7L, 4L, 6L, 
                                                                                                                                                                              5L, 5L, 5L, 7L, 6L, 6L, 5L, 3L, 4L, 5L, 5L, 5L, 6L, 4L, 5L, 4L, 
                                                                                                                                                                              4L, 7L, 7L, 4L, 4L, 4L, 5L, 5L, 4L, 6L, 4L, 6L, 7L, 7L, 5L, 7L, 
                                                                                                                                                                              6L, 6L, 5L, 3L, 7L, 6L, 5L, 4L, 5L, 4L, 7L, 4L, 5L, 6L, 4L, 5L, 
                                                                                                                                                                              5L, 6L, 6L, 4L, 4L, 5L, 5L, 7L, 7L, 7L, 6L, 6L, 7L, 4L, 6L, 6L, 
                                                                                                                                                                              6L, 4L, 4L, 4L, 7L, 5L, 6L, 6L, 5L, 5L, 5L, 2L, 6L, 6L, 7L, 5L, 
                                                                                                                                                                              7L, 4L, 7L, 7L, 4L, 7L, 7L, 4L, 4L, 6L, 4L, 6L, 7L, 4L, 4L, 6L, 
                                                                                                                                                                              4L, 5L, 7L, 4L, 5L, 4L, 7L, 5L, 4L, 6L, 6L, 7L, 7L, 5L, 5L, 7L, 
                                                                                                                                                                              7L, 4L, 6L, 5L, 5L, 6L, 4L, 7L, 5L, 4L, 5L, 6L, 6L, 6L, 4L, 5L, 
                                                                                                                                                                              5L, 5L, 6L, 5L, 5L, 4L, 7L, 6L, 5L, 4L, 7L, 5L, 7L, 6L, 4L, 4L, 
                                                                                                                                                                              7L, 4L, 5L, 6L, 4L, 6L, 5L, 5L, 4L, 6L, 5L, 4L, 5L, 6L, 4L, 7L, 
                                                                                                                                                                              7L, 5L, 4L, 4L, 7L, 4L, 5L, 3L, 3L, 4L, 4L, 5L, 6L, 4L, 6L, 6L, 
                                                                                                                                                                              6L, 7L, 5L, 7L, 5L, 5L, 7L, 6L, 7L, 4L, 6L, 7L, 4L, 7L, 7L, 4L, 
                                                                                                                                                                              7L, 5L, 4L, 5L, 4L, 7L, 4L, 6L, 6L, 4L, 4L, 4L, 4L, 7L, 7L, 7L, 
                                                                                                                                                                              6L, 4L, 7L, 7L, 7L, 5L, 6L, 5L, 5L, 7L, 6L, 5L, 5L, 5L, 6L, 6L, 
                                                                                                                                                                              4L, 6L, 4L, 7L, 6L, 4L, 6L, 6L, 4L, 6L, 3L, 7L, 4L, 6L, 4L, 4L, 
                                                                                                                                                                              5L, 4L, 7L, 6L, 6L, 4L, 4L, 6L, 5L, 4L, 6L, 6L, 4L, 4L, 6L, 4L, 
                                                                                                                                                                              6L, 7L, 6L, 6L, 5L, 4L, 5L, 5L, 7L, 6L, 5L, 5L, 4L, 7L, 4L, 7L, 
                                                                                                                                                                              4L, 6L, 7L, 3L, 6L, 6L, 6L, 6L, 4L, 7L, 7L, 7L, 4L, 5L, 4L, 6L, 
                                                                                                                                                                              5L, 7L, 5L)), row.names = c(NA, -409L), class = "data.frame")