swirl_options(swirl_logging = TRUE)
pain <- structure(list(rowid = c(1L, 1L, 1L, 2L, 2L, 2L, 3L, 3L, 3L, 
                                 4L, 4L, 4L, 5L, 5L, 5L, 6L, 6L, 6L, 7L, 7L, 7L, 8L, 8L, 8L, 9L, 
                                 9L, 9L, 10L, 10L, 10L, 11L, 11L, 11L, 12L, 12L, 12L, 13L, 13L, 
                                 13L, 14L, 14L, 14L, 15L, 15L, 15L, 16L, 16L, 16L, 17L, 17L, 17L, 
                                 18L, 18L, 18L, 19L, 19L, 19L, 20L, 20L, 20L, 21L, 21L, 21L, 22L, 
                                 22L, 22L, 23L, 23L, 23L, 24L, 24L, 24L, 25L, 25L, 25L, 26L, 26L, 
                                 26L, 27L, 27L, 27L, 28L, 28L, 28L, 29L, 29L, 29L, 30L, 30L, 30L, 
                                 31L, 31L, 31L, 32L, 32L, 32L, 33L, 33L, 33L, 34L, 34L, 34L, 35L, 
                                 35L, 35L, 36L, 36L, 36L, 37L, 37L, 37L, 38L, 38L, 38L, 39L, 39L, 
                                 39L, 40L, 40L, 40L, 41L, 41L, 41L, 42L, 42L, 42L, 43L, 43L, 43L, 
                                 44L, 44L, 44L, 45L, 45L, 45L, 46L, 46L, 46L, 47L, 47L, 47L, 48L, 
                                 48L, 48L), Feedback = c("Understated", "Accurate", 
                                 "Overstated", "Understated", 
                                 "Accurate", "Overstated", "Understated", 
                                 "Accurate", "Overstated", "Understated", 
                                 "Accurate", "Overstated", "Understated", 
                                 "Accurate", "Overstated", "Understated", 
                                 "Accurate", "Overstated", "Understated", 
                                 "Accurate", "Overstated", "Understated", 
                                 "Accurate", "Overstated", "Understated", 
                                 "Accurate", "Overstated", "Understated", 
                                 "Accurate", "Overstated", "Understated", 
                                 "Accurate", "Overstated", "Understated", 
                                 "Accurate", "Overstated", "Understated", 
                                 "Accurate", "Overstated", "Understated", 
                                 "Accurate", "Overstated", "Understated", 
                                 "Accurate", "Overstated", "Understated", 
                                 "Accurate", "Overstated", "Understated", 
                                 "Accurate", "Overstated", "Understated", 
                                 "Accurate", "Overstated", "Understated", 
                                 "Accurate", "Overstated", "Understated", 
                                 "Accurate", "Overstated", "Understated", 
                                 "Accurate", "Overstated", "Understated", 
                                 "Accurate", "Overstated", "Understated", 
                                 "Accurate", "Overstated", "Understated", 
                                 "Accurate", "Overstated", "Understated", 
                                 "Accurate", "Overstated", "Understated", 
                                 "Accurate", "Overstated", "Understated", 
                                 "Accurate", "Overstated", "Understated", 
                                 "Accurate", "Overstated", "Understated", 
                                 "Accurate", "Overstated", "Understated", 
                                 "Accurate", "Overstated", "Understated", 
                                 "Accurate", "Overstated", "Understated", 
                                 "Accurate", "Overstated", "Understated", 
                                 "Accurate", "Overstated", "Understated", 
                                 "Accurate", "Overstated", "Understated", 
                                 "Accurate", "Overstated", "Understated", 
                                 "Accurate", "Overstated", "Understated", 
                                 "Accurate", "Overstated", "Understated", 
                                 "Accurate", "Overstated", "Understated", 
                                 "Accurate", "Overstated", "Understated", 
                                 "Accurate", "Overstated", "Understated", 
                                 "Accurate", "Overstated", "Understated", 
                                 "Accurate", "Overstated", "Understated", 
                                 "Accurate", "Overstated", "Understated", 
                                 "Accurate", "Overstated", "Understated", 
                                 "Accurate", "Overstated", "Understated", 
                                 "Accurate", "Overstated", "Understated", 
                                 "Accurate", "Overstated", "Understated", 
                                 "Accurate", "Overstated"), Rotation = c(0.88, 
                                 1, 1.11, 0.94, 1, 0.92, 1.01, 1, 0.97, 1.21, 1, 1.04, 1.3, 1, 
                                 0.78, 1.32, 1, 0.85, 1.4, 1, 0.89, 1.16, 1, 0.94, 1.28, 1, 0.77, 
                                 1.15, 1, 1.1, 0.97, 1, 1.07, 1.09, 1, 0.81, 0.84, 1, 0.97, 0.98, 
                                 1, 0.99, 1.06, 1, 1.09, 0.94, 1, 0.97, 0.89, 1, 0.79, 1.05, 1, 
                                 0.88, 1.09, 1, 1.04, 1.21, 1, 0.85, 0.93, 1, 0.9, 1.05, 1, 1.16, 
                                 1.19, 1, 0.85, 1.03, 1, 0.92, 0.83, 1, 0.85, 0.95, 1, 1.08, 1.04, 
                                 1, 1, 1.06, 1, 0.91, 0.98, 1, 0.69, 0.91, 1, 0.86, 1.33, 1, 0.92, 
                                 0.94, 1, 0.82, 0.89, 1, 0.63, 1.03, 1, 1.02, 0.97, 1, 0.93, 1.17, 
                                 1, 1.07, 0.97, 1, 0.94, 1.13, 1, 1.02, 1.07, 1, 1, 1.07, 1, 0.88, 
                                 1.26, 1, 1.13, 1.18, 1, 0.86, 1, 1, 0.97, 1.26, 1, 0.88, 1.12, 
                                 1, 0.71, 0.96, 1, 0.91, 0.98, 1, 0.81, 1.07, 1, 1.15)), class = c("tbl_df", 
                                                                               "tbl", "data.frame"), row.names = c(NA, -144L))

pain$rowid <- as.factor(pain$rowid)
pain$Feedback <- as.factor(pain$Feedback)
